### ISSUE TITLE
404 bei Link auf Readme

### ISSUE THREAD

**Issue by OfficialCRUGG** [d3d9/hst-svg-netzplan#16]
Hey!
Ich habe die in der Readme aufgelisteten Links angesehen. Der zweite Link (https://d3d9.github.io/hst-svg-netzplan/) funktioniert zwar, jedoch tut dies der erste (https://d3d9.xyz/osm/hstsvg/) nicht. Ich würde vorschlagen, diesen Link endweder zu reparieren, oder ihn aus der Readme zu entfernen! :)

**Comment by d3d9** [comment]
Ah ja, danke.  
Habe bei der Umstellung meiner Seite (und gleichzeitigem Entfernen vom dort vorhandenen Verzeichnis) nur das Kürzel `d3d9.xyz/s` aktualisiert, aber nicht `/osm/hstsvg/` mit einer Umleitung versorgt, weil ich dachte, dass das sowieso kaum jemand direkt aufruft -- voll vergessen, dass von der Readme noch darauf verlinkt wird.
